### ISSUE TITLE
Connect a webhook to github

### ISSUE THREAD

**Issue by yazpik** [Tlacuaches/tlacuaches#11]
- Use slack webhook + github to post notification under Tlacuaches slack channel, when a Push, Merge, etc happen

**Comment by tuxisma** [comment]
cool! I will work on it.

**Comment by tuxisma** [comment]
done!  I've connected Slack webhook and github to post notification under Tlacuaches slack channel, showing Push, Pull Request, Merge, Fork and all activities on Tlacuaches Chanel.

**Comment by fmoctezuma** [comment]
Nice work @tuxisma , closing this issue then!

**Comment by tuxisma** [comment]
...
