### ISSUE TITLE
Bonus task - Let's encrypt

### ISSUE THREAD

**Issue by fmoctezuma** [Tlacuaches/tlacuaches#25]
@tuxisma 
Per our conversation,
Extra Mission 🚀 
Deploy ghost or any other webservice/content management and enable let's encrypt, use the kubernetes ingress controller on your minikube, and nip.io or similar for dns fwd.

Let's talk about monitoring later.

**Comment by fmoctezuma** [comment]
Should I close this one @tuxisma ?

**Comment by tuxisma** [comment]
Not yet please, finding time to complete, I will work on it .

**Comment by tuxisma** [comment]
I've created a image of my blog with hugo hosted in Docker hub: 
[myimage](https://hub.docker.com/r/tuxisma/blog/tags/
)
Then
I will deploy it using Kubernetes
-----------------------
Regards
