### ISSUE TITLE
Etherpad installation

### ISSUE THREAD

**Issue by yazpik** [Tlacuaches/tlacuaches#4]
Deploy etherpad on docker

**Comment by yazpik** [comment]
I have created a directory "Dockerfiles" on our repo, so feel free to push your dockerfile and work from there 🗡

**Comment by tuxisma** [comment]
Cool! I'm testing some containers on my VM after that I will install docker on node1.

**Comment by tuxisma** [comment]
etherpad running on docker successfully.

**Comment by fmoctezuma** [comment]
nice job!
