### ISSUE TITLE
Deploy openstack on node2

### ISSUE THREAD

**Issue by yazpik** [Tlacuaches/tlacuaches#5]
node-2 deployment

**Comment by yazpik** [comment]
See docs https://docs.openstack.org/openstack-ansible/newton/developer-docs/quickstart-aio.html

**Comment by yazpik** [comment]
moving this one to Javier, once he shares his github account

**Comment by yazpik** [comment]
@jasanz25 Please use this documentation to deploy an All-in-one Openstack cluster based on the latest stable release for OpenStack Ansible.
https://docs.openstack.org/openstack-ansible/newton/developer-docs/quickstart-aio.html

Let me know if you have any question or concern

**Comment by yazpik** [comment]
Hey where are we on this ? I don't see any updates on this issue since 29 days now...
Can you provide an update ? @jasanz25

**Comment by fmoctezuma** [comment]
closing this due lack of interest, reopening for tlacuaches 0.2 project
