### ISSUE TITLE
Security hardening node0

### ISSUE THREAD

**Issue by yazpik** [Tlacuaches/tlacuaches#6]
**Pre-reqs Ansible**
Read the actual script to have an idea what is going on 
**NOTE:** I have tested it for US only, just added MX, so probably you will get locked (hopefully not)
`ansible-playbook <path to script>aio-security-hardening.yml`

https://gist.github.com/yazpik/0f9fd005802ac068bd1b19f85549a66f

**Comment by diegoaguilar** [comment]
Downlodaded the playbook script and ran it with ansible

**Comment by fmoctezuma** [comment]
reopening because I'm lazy, @tuxisma give it a try!

**Comment by fmoctezuma** [comment]
**NOTE:** do it with node1

**Comment by tuxisma** [comment]
done, ansible-playbook  runnig on node-1.

**Comment by fmoctezuma** [comment]
did you restart ssh service already and tested access?

**Comment by tuxisma** [comment]
sure!
